---
title: "Mini Project 3"
author: "Ivana William and Haiqa Mohamed"
date: "March 21, 2018"
output: html_document
code_folding: hide
---

```{r setup, echo = FALSE, message = FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
```

```{r, echo = FALSE, message = FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r setup, echo = FALSE, message = FALSE}
poll_results <- house_elections%>%
mutate(Total_votes = general_votes + primary_votes) 
```
```{r}
northeast_contributions <- contributions%>%  
  filter(state %in% c("CT","MA","NH","NJ","NY","PA"))
```

used Inner-join to join contributions and votes by "state"
```{r setup, echo = FALSE, message = FALSE}
northeast <- poll_results%>%
 filter(state %in% c("CT","MA","NH","NJ","NY","PA"))
```
<<<<<<< HEAD
used Inner-join to join contributions and votes by "state". Then created a new dataset that has the contribution and votes data sets but filtered for the 6 Northeastern states. We then grouped by party and state and summarised by transaction amount to make the data more managable

```{r}
contributions_votes <- northeast_contributions %>% inner_join(northeast, by="state")

contributions_votes2 <- contributions_votes %>% filter(state %in% c("CT","MA","NH","NJ","NY","PA"))%>%
  group_by(party, state) %>%
  summarise(sum = sum(transaction_amt))
```

graph 2
```{r}
poll_graph <- ggplot(northeast, aes(x = "CT","MA","NH","NJ","NY","PA")) +
  geom_bar(aes(fill = party)) +  xlab("State")+
  ylab("Total Votes") + scale_fill_manual(values=c("BLUE", "RED")) 
=======
```{r}
northeast_contributions %>% inner_join(northeast, by="state")
```


```{r}
poll_graph <- ggplot(northeast, aes(x = "CT","MA","NH","NJ","NY","PA" , y = Total_votes, fill = party)) +
  geom_bar(stat = "identity", position = "dodge")+
  xlab("State")+
  ylab("Total Votes") + facet_wrap(~state) + scale_fill_manual(values=c("BLUE", "RED")) 
>>>>>>> ca77fc21055ca7234047ebf9a3b5b1eae29f6724
  
poll_graph
```


<<<<<<< HEAD
```{r}
poll_graph <- ggplot(contributions_votes2, aes(x = party, y = sum)) +
  geom_bar(stat = "identity") + facet_wrap(~state)
  

poll_graph
```






=======
>>>>>>> ca77fc21055ca7234047ebf9a3b5b1eae29f6724
